[build]
  command = "npm run build:js"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"  # If you're using serverless for SSR, otherwise update to serve your `server.js`
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Custom-Toml = "Toml"
